//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _HEROARCADEDRIVE__H_
#define _HEROARCADEDRIVE__H_

#include <TinyCLR_Interop.h>
struct Library_HeroArcadeDrive__Hero_Arcade_Drive_Program
{
    static const int FIELD_STATIC__rightSlave = 0;
    static const int FIELD_STATIC__right = 1;
    static const int FIELD_STATIC__leftSlave = 2;
    static const int FIELD_STATIC__left = 3;
    static const int FIELD_STATIC__pdp = 4;
    static const int FIELD_STATIC__stringBuilder = 5;
    static const int FIELD_STATIC__Joy = 6;
    static const int FIELD_STATIC__low_battery_pin = 7;
    static const int FIELD_STATIC__connection_pin = 8;
    static const int FIELD_STATIC__current_pin = 9;
    static const int FIELD_STATIC__power_pin = 10;
    static const int FIELD_STATIC__brownout_pin = 11;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative__HeroArcadeDrive;

#endif  //_HEROARCADEDRIVE__H_
